---
title: "Minnow Project"
author: "Gabriella Commisso"
date: "2024-06-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r loading required packages}
require(fishtree)
require(phytools)
require(geiger)
require(ape)
require(geomorph)
require(ggplot2)
require(ggpubr)
```

```{r loading dataset and checking phylogenetics}

#reading Rabosky et al. 2018 tree
tree<-fishtree_phylogeny()

#uploading data
minnow_data <- readxl::read_xlsx("C:/Users/Test 1/OneDrive/Documents/AbCav Project/data_ouwie.xlsx")

#checking data against tree
rownames(minnow_data) <- minnow_data$Species
d<-name.check(tree, minnow_data) 
d

#dropping excess species
phy.mcc <- drop.tip(tree,d$tree_not_data)
plot(phy.mcc, cex = 0.8)
write.nexus(phy.mcc, file = "C:/Users/Test 1/OneDrive/Documents/AbCav Project/droptiptree.nexus", translate = TRUE)
```

```{r labelling variables}
size<-minnow_data$`Standard Length`
names(size)<-rownames(minnow_data)
maxlgn<-minnow_data$`Max Length`
names(maxlgn)<-rownames(minnow_data)
diet<-minnow_data$Trophic
names(diet)<-rownames(minnow_data)
acv <- minnow_data$ABV
names(acv) <- rownames(minnow_data)
itl <- minnow_data$`Intestine Length`
names(itl) <- rownames(minnow_data)
acv.log <- minnow_data$ABV_log
names(acv.log) <- rownames(minnow_data)
itl.log <- minnow_data$IL_log
names(itl.log) <- rownames(minnow_data)
sc.itl <- minnow_data$IL_resid
names(sc.itl) <- rownames(minnow_data)
sc.acv <- minnow_data$ABV_resid
names(sc.acv) <- rownames(minnow_data)
```


```{r ggplot body length vs intestine length}
pglsmodel1<-procD.pgls(itl.log ~ log(size), phy=phy.mcc, iter = 10000)
summary(pglsmodel1)
coef1 <- coefficients(pglsmodel1)
intercept1<-coef1[1] 
slope1<- coef1[2]
reg1<-ggplot(minnow_data,aes(log(size),itl.log, color=Trophic))+
  scale_color_manual(values = c("HD" = "#33a02c", "AquaticInvertivore"="#b2df8a", "Omnivore"="grey", "AquaticInsectivore"="#a6cee3", "InsectLarvaphage"="#1f78b4", "Carnivore"="black"))+
  geom_point(size=2.5)+
  geom_abline(intercept = intercept1, slope = slope1, color="red")+ 
  ylab("Log-Int Length (mm)")+
  xlab("Log-Body Length (mm)")+
  annotate("text", x=3.75, y=2.8, label= "R = 0.648")
reg1
```

```{r ggplot body length vs abdominal cavity volume}
pglsmodel2<-procD.pgls(acv.log ~ log(size), phy=phy.mcc, iter = 10000)
summary(pglsmodel2)
coef2 <- coefficients(pglsmodel2)
intercept2<-coef2[1] 
slope2<- coef2[2]
reg2<-ggplot(minnow_data,aes(log(size),acv.log, color=Trophic))+
  scale_color_manual(values = c("HD" = "#33a02c", "AquaticInvertivore"="#b2df8a", "Omnivore"="grey", "AquaticInsectivore"="#a6cee3", "InsectLarvaphage"="#1f78b4", "Carnivore"="black"))+
  geom_point(size=2.5)+
  geom_abline(intercept = intercept2, slope = slope2, color="red")+ 
  ylab("Log-AbCav Vol (mm3)")+
  xlab("Log-Body Length (mm)")+
  annotate("text", x=3.75, y=3.9, label= "R = 0.876")
reg2
```

```{r ggplot intestine length vs abdominal cavity volume}
pglsmodel3<-procD.pgls(acv.log ~ itl.log, phy=phy.mcc, iter = 10000)
summary(pglsmodel3)
coef3 <- coefficients(pglsmodel3)
intercept3<-coef3[1] 
slope3<- coef3[2]
reg3<-ggplot(minnow_data,aes(itl.log, acv.log, color=Trophic))+
  scale_color_manual(values = c("HD" = "#33a02c", "AquaticInvertivore"="#b2df8a", "Omnivore"="grey", "AquaticInsectivore"="#a6cee3", "InsectLarvaphage"="#1f78b4", "Carnivore"="black"))+
  geom_point(size=2.5)+
  geom_abline(intercept = intercept3, slope = slope3, color="red")+ 
  ylab("Log-AbCav Vol (mm3)")+
  xlab("Log-Int Length (mm)")+
  annotate("text", x=1.4, y=3.9, label= "R = 0.489")
reg3
```

```{r creating regression figure for paper}
reg_figure <- ggarrange(reg1, reg2, reg3,
                    labels = c("a", "b", "c"),
                    ncol = 1, nrow = 3)
reg_figure
```

```{r size-corrected intestine length vs trophic group}
box1<-ggplot(minnow_data,aes(Trophic, sc.itl, fill=Trophic))+
  geom_boxplot()+
  scale_fill_manual(values = c("HD" = "#33a02c", "AquaticInvertivore"="#b2df8a", "Omnivore"="grey", "AquaticInsectivore"="#a6cee3", "InsectLarvaphage"="#1f78b4", "Carnivore"="black"))+
  ylab("Size-Corrected Intestine Length")+
  xlab("Trophic Group")+
  theme(legend.position='none', axis.text.x = element_blank())
box1
eco<-minnow_data$Trophic
names(eco)<-rownames(minnow_data)
trophic.anova<-procD.pgls(sc.itl~eco, phy=phy.mcc, iter = 10000)
summary(trophic.anova)
gp <-  interaction (eco)
PW <- pairwise(trophic.anova, groups = gp, covariate = NULL)
summary(PW)
```

```{r size-corrected ab cav/trophic group}
box2<-ggplot(minnow_data,aes(Trophic, sc.acv, fill=Trophic))+
  geom_boxplot()+
  scale_fill_manual(values = c("HD" = "#33a02c", "AquaticInvertivore"="#b2df8a", "Omnivore"="grey", "AquaticInsectivore"="#a6cee3", "InsectLarvaphage"="#1f78b4", "Carnivore"="black"))+
  ylab("Size-Corrected Abdominal Cavity Vol")+
  xlab("Trophic Group")+
  theme(legend.position='none', axis.text.x = element_blank())
box2
eco<-minnow_data$Trophic
names(eco)<-rownames(minnow_data)
trophic.anova<-procD.pgls(sc.acv~eco, phy=phy.mcc, iter = 10000)
summary(trophic.anova)
gp <-  interaction (eco)
PW <- pairwise(trophic.anova, groups = gp, covariate = NULL)
summary(PW)
```

```{r measured body length/trophic group}
box3<-ggplot(minnow_data,aes(Trophic, log(size), fill=Trophic))+
  geom_boxplot()+
  scale_fill_manual(values = c("HD" = "#33a02c", "AquaticInvertivore"="#b2df8a", "Omnivore"="grey", "AquaticInsectivore"="#a6cee3", "InsectLarvaphage"="#1f78b4", "Carnivore"="black"))+
  ylab("Log Body Length")+
  xlab("Trophic Group")+
  theme(legend.position='none', axis.text.x = element_blank())
box3
eco<-minnow_data$Trophic
names(eco)<-rownames(minnow_data)
trophic.anova<-procD.pgls(log(size)~eco, phy=phy.mcc, iter = 10000)
summary(trophic.anova)
gp <-  interaction (eco)
PW <- pairwise(trophic.anova, groups = gp, covariate = NULL)
summary(PW)
```

```{r max body length/trophic}
box4<-ggplot(minnow_data,aes(Trophic, log(maxlgn), fill=Trophic))+
  geom_boxplot()+
  scale_fill_manual(values = c("HD" = "#33a02c", "AquaticInvertivore"="#b2df8a", "Omnivore"="grey", "AquaticInsectivore"="#a6cee3", "InsectLarvaphage"="#1f78b4", "Carnivore"="black"))+
  ylab("Log Maximum Body Length")+
  xlab("Trophic Group")
box4
eco<-minnow_data$Trophic
names(eco)<-rownames(minnow_data)
trophic.anova<-procD.pgls(log(maxlgn)~eco, phy=phy.mcc, iter = 10000)
summary(trophic.anova)
gp <-  interaction (eco)
PW <- pairwise(trophic.anova, groups = gp, covariate = NULL)
summary(PW)
```

```{r creating regression figure for paper}
box_figure <- ggarrange(box1, box2, box3,
                    labels = c("a", "b", "c"),
                    ncol = 3, nrow = 1)
box_figure
```

```{r size-corrected supplementary figures}
#body length/int length
pglsmodel4<-procD.pgls(sc.itl ~ log(size), phy=phy.mcc, iter = 10000)
summary(pglsmodel4)
coef4 <- coefficients(pglsmodel4)
intercept4<-coef4[1] 
slope4<- coef4[2]
reg4<-ggplot(minnow_data,aes(log(size), sc.itl, color=Trophic))+
  scale_color_manual(values = c("HD" = "#33a02c", "AquaticInvertivore"="#b2df8a", "Omnivore"="grey", "AquaticInsectivore"="#a6cee3", "InsectLarvaphage"="#1f78b4", "Carnivore"="black"))+
  geom_point(size=2.5)+
  geom_abline(intercept = intercept4, slope = slope4, color="red")+ 
  ylab("Size-Cor Int Length (mm)")+
  xlab("Log- Body Length (mm)")+
  annotate("text", x=3.75, y=2.8, label= "R = 0.00005")
reg4
#body length/abcav vol
pglsmodel5<-procD.pgls(sc.acv ~ log(size), phy=phy.mcc, iter = 10000)
summary(pglsmodel5)
coef5 <- coefficients(pglsmodel5)
intercept5<-coef5[1] 
slope5<- coef5[2]
reg5<-ggplot(minnow_data,aes(log(size), sc.acv, color=Trophic))+
  scale_color_manual(values = c("HD" = "#33a02c", "AquaticInvertivore"="#b2df8a", "Omnivore"="grey", "AquaticInsectivore"="#a6cee3", "InsectLarvaphage"="#1f78b4", "Carnivore"="black"))+
  geom_point(size=2.5)+
  geom_abline(intercept = intercept5, slope = slope5, color="red")+ 
  ylab("Size-Cor AbCav Vol (mm3)")+
  xlab("Log- Body Length (mm)")+
  annotate("text", x=3.75, y=2.8, label= "R = 0.00001")
reg5
#intestine length/abcav
pglsmodel6<-procD.pgls(sc.acv ~ sc.itl, phy=phy.mcc, iter = 10000)
summary(pglsmodel6)
coef6 <- coefficients(pglsmodel6)
intercept6<-coef6[1] 
slope6<- coef6[2]
reg6<-ggplot(minnow_data,aes(sc.itl, sc.acv, color=Trophic))+
  scale_color_manual(values = c("HD" = "#33a02c", "AquaticInvertivore"="#b2df8a", "Omnivore"="grey", "AquaticInsectivore"="#a6cee3", "InsectLarvaphage"="#1f78b4", "Carnivore"="black"))+
  geom_point(size=2.5)+
  geom_abline(intercept = intercept6, slope = slope6, color="red")+ 
  ylab("Size-Cor AbCav Vol (mm3)")+
  xlab("Size-Cor Int Length (mm)")+
  annotate("text", x=-0.75, y=1, label= "R = 0.069")
reg6
```

```{r sup fig 1}
sup_figure <- ggarrange(reg4, reg5, reg6,
                    labels = c("a", "b", "c"),
                    ncol = 1, nrow = 3)
sup_figure
```

```{r sup boxplots}
#log intestine length
box5<-ggplot(minnow_data,aes(Trophic, itl.log, fill=Trophic))+
  geom_boxplot()+
  scale_fill_manual(values = c("HD" = "#33a02c", "AquaticInvertivore"="#b2df8a", "Omnivore"="grey", "AquaticInsectivore"="#a6cee3", "InsectLarvaphage"="#1f78b4", "Carnivore"="black"))+
  ylab("Log-Adjusted Intestine Length")+
  xlab("Trophic Group")+
  theme(legend.position='none', axis.text.x = element_blank())
box5
eco<-minnow_data$Trophic
names(eco)<-rownames(minnow_data)
trophic.anova<-procD.pgls(itl.log~eco, phy=phy.mcc, iter = 10000)
summary(trophic.anova)
gp <-  interaction (eco)
PW <- pairwise(trophic.anova, groups = gp, covariate = NULL)
summary(PW)
#log ab cav volume
box6<-ggplot(minnow_data,aes(Trophic, acv.log, fill=Trophic))+
  geom_boxplot()+
  scale_fill_manual(values = c("HD" = "#33a02c", "AquaticInvertivore"="#b2df8a", "Omnivore"="grey", "AquaticInsectivore"="#a6cee3", "InsectLarvaphage"="#1f78b4", "Carnivore"="black"))+
  ylab("Log-Adjusted Abdominal Cavity Vol")+
  xlab("Trophic Group")+
  theme(legend.position='none', axis.text.x = element_blank())
box6
eco<-minnow_data$Trophic
names(eco)<-rownames(minnow_data)
trophic.anova<-procD.pgls(acv.log~eco, phy=phy.mcc, iter = 10000)
summary(trophic.anova)
gp <-  interaction (eco)
PW <- pairwise(trophic.anova, groups = gp, covariate = NULL)
summary(PW)
```